paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: assets
  uploads: assets/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    _enabled_editors:
      - visual
    path: content
    description: Pages description
    output: true
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      page:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /
      detail_page:
        path: .cloudcannon/schemas/detail-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /detail-preview/
      guide_page:
        path: .cloudcannon/schemas/guide-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /guide-preview/
      guide_page_index:
        path: .cloudcannon/schemas/guide-page-index.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /guide-preview/
        create:
          path: '[relative_base_path]/_index.md'
      student_profile:
        path: .cloudcannon/schemas/student-profile.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /previews/student-profile/
  articles:
    _enabled_editors:
      - visual
    path: content/articles
    description: Articles description
    icon: edit
    output: true
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      article:
        path: .cloudcannon/schemas/article.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /
  data:
    path: data
    description: Data that is used to populate multiple areas throughout the site
    output: false
    icon: data_usage
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  # people:
  #   path: data/people.yml
  #   description: Data for people
  #   output: false
  #   disable_add: false
  #   disable_add_folder: true
  #   disable_file_actions: false
  #   icon: group
  default_content:
    icon: toolbar
    path: data/default_content
  people:
    path: content/people
    add_options:
      - name: Faculty Member
        schema: faculty
      - name: Speaker
        schema: speaker
      - name: Staff Member
        schema: staff
      - name: Student
        schema: student
    icon: group
    schemas:
      faculty:
        path: .cloudcannon/schemas/faculty.yml
      speaker:
        path: .cloudcannon/schemas/speaker.yml
      staff:
        path: .cloudcannon/schemas/staff.yml
      student:
        path: .cloudcannon/schemas/student-profile.md
  links:
    icon: link
    path: data/links.yml
    schemas:
      links:
        path: .cloudcannon/schemas/links.yml
  partners:
    path: data/partners.yml
    add_options:
      - name: Partner
        schema: partners
    icon: handshake
    schemas:
      partners:
        path: .cloudcannon/schemas/partners.yml
  places_and_spaces:
    path: data/places_and_spaces
    add_options:
      - name: Facility
        schema: facility
    icon: location_on
    schemas:
      facility:
        path: .cloudcannon/schemas/facilities.yml
  site_config:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    icon: settings
    path: data/site_config
  sitewide_components:
    path: data/sitewide_components
    description: Sitewide components
    output: false
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    icon: variable_add
    schemas:
      sitewide_quicklinks:
        path: .cloudcannon/schemas/sitewide-quicklinks.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
collection_groups:
  - heading: Pages
    collections:
      - pages
      - articles
  - heading: Collections
    collections:
      - links
      - partners
      - people
      - places_and_spaces
      # - programs
  - heading: Site
    collections:
      - site_config
      - default_content
      - sitewide_components
#   - heading: Site Config
#     collections:
#       - site_config
#   - heading: Data
#     collections:
#       - data
_enabled_editors:
  - visual
  - content
  - data
_select_data:
  alert_type:
    - name: Danger
      type: danger
    - name: Info
      type: info
    - name: Warning
      type: warning
  brand_colors:
    - name: WVU Gold
      class: wvu-gold 
    - name: WVU Blue
      class: wvu-blue
    - name: Accent - Blue
      class: wvu-accent--blue
    - name: Accent - Dark Blue
      class: wvu-accent--blue-dark
    - name: Accent - Light Blue
      class: wvu-accent--blue-light
    - name: Accent - Yellow
      class: wvu-accent--yellow
    - name: Accent - Old Gold
      class: wvu-accent--old-gold
    - name: Accent - Sunset
      class: wvu-accent--sunset
    - name: Neutral - Off-White
      class: wvu-neutral--off-white
    - name: Neutral - Warm Gray Light
      class: wvu-neutral--warm-gray-light
    - name: Neutral - Warm Gray Medium
      class: wvu-neutral--warm-gray-medium
    - name: Neutral - Warm Gray Dark
      class: wvu-neutral--warm-gray-dark
    - name: Neutral - Cream
      class: wvu-neutral--cream
    - name: Neutral - Tan
      class: wvu-neutral--tan
  typography_palettes:
    - name: WVU Experience
      palette: wvu_experience
    - name: Down to Business
      palette: down_to_business
    - name: Discovery
      palette: discovery
    - name: Nostalgic
      palette: nostalgic
_inputs:
  alert_message:
    type: markdown
  alert_status:
    type: switch
  alert_type:
    type: select
    options:
      values:
        - _select_data.alert_type
      value_key: type
  color:
    type: select
    options:
      allow_empty: true
      values:
        - _select_data.brand_colors
      value_key: class
  ctas:
    type: array
    options:
      structures: _structures.links
  edit_mode_only:
    type: switch
  excerpt:
    type: markdown
  hide:
    type: datetime
  id:
    hidden: true
    instance_value: UUID
  image:
    type: object
    context:
      icon: add_a_photo
    options:
      structures: _structures.image
  limit:
    type: number
  message:
    type: markdown
  person:
    type: select
    options:
      allow_empty: true
      values: data.people
  postscript_links:
    type: array
    options:
      structures: _structures.links
  publish_date:
    type: date
    instance_value: NOW
  show_author_bios:
    type: switch
  student:
    type: select
    options:
      allow_empty: true
      values: data.people.students
  student_profile_topper:
    type: object
    options:
      structures: _structures.student_profile_topper
  topper:
    type: object
    options:
      structures: _structures.topper
  topper_type:
    hidden: true
  typography:
    type: select
    options:
      values: _select_data.typography_palettes
      value_key: palette
  show:
    type: datetime
  src:
    type: image
  type:
    type: auto
    hidden: true
    cascade: true
  layout:
    hidden: true
  site_page:
    type: select
    options:
      allow_empty: true
      preview:
        text:
          - key: title
      values: data.site_pages
      value_key: id
  sitewide_section:
    type: select
    options:
      allow_empty: true
      values: data.sitewide_components
  styles_button:
    hidden: true
  styles_h1:
    hidden: true
  styles_h1_label:
    hidden: true
  styles_h2:
    hidden: true
  styles_h2_label:
    hidden: true
  styles_lead:
    hidden: true
  styles_section:
    hidden: true
  tags:
    type: multiselect
    options:
      allow_create: true
      allow_empty: true
      values:
        - featured
_structures:
  background_layers:
    values:
      - label: Background Color
        value:
          color:
    background_c: 
  content_blocks:
    style: modal
  detail_blocks:
    style: modal
  # factoids:
  #   values:
  #     - pre:
  #       stat:
  #       post:
  #       source:
  image:
    values:
      - value:
          src:
          alt:
  links:
    values:
      - value:
          ref:
          text:
          icon:
          url:
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    snippet: true
    strike: true
    styles: /assets/scss/custom/_content.scss
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
data_config: true
timezone: US/Eastern
_snippets:
  figure:
    template: hugo_shortcode_named_args
    inline: false
    picker_preview:
      gallery:
        image: .cloudcannon/shortcode_previews/figure.webp
        icon: image
      text: Figure
      icon: image
      subtext: An image with an optional caption below
    preview:
      view: gallery
      gallery:
        image:
          - key: image_source
      text:
        - key: image_alt
        - Image has no alternative text
      icon: image
      metadata:
        - icon: folder
          text:
            - key: image_source
        - icon: closed_caption
          text:
            - key: caption
    definitions:
      shortcode_name: figure
      named_args:
        - editor_key: image_source
          type: string
          optional: false
        - editor_key: image_alt
          type: string
          optional: false
        - editor_key: caption
          type: string
          optional: true
    _inputs:
      image_source:
        type: image
        cascade: true
      caption:
        type: textarea
        cascade: true
  blockquote:
    template: hugo_shortcode_named_args
    inline: false
    picker_preview:
      gallery:
        image: .cloudcannon/shortcode_previews/blockquote.webp
        icon: format_quote
      text: Blockquote
      icon: format_quote
    preview:
      text:
        - key: quote
        - Quote
      icon: format_quote
      metadata:
        - text:
            - key: author
          icon: account_box
    definitions:
      shortcode_name: blockquote
      named_args:
        - editor_key: quote
          type: string
          optional: false
        - editor_key: author
          type: string
          optional: false
    _inputs:
      quote:
        type: textarea
        cascade: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_figure