paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: assets
  uploads: assets/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  articles:
    _enabled_editors:
      - visual
      - data
    path: content/articles
    description: Articles description
    icon: edit
    output: true
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      article:
        path: .cloudcannon/schemas/article.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /
  clubs_and_organizations:
    _enabled_editors:
      - visual
      - data
    path: content/clubs-and-organizations
    description: Clubs and organizations.
    icon:
    output: true
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      clubs_and_organizations:
        path: .cloudcannon/schemas/organization.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /
  data:
    path: data
    description: Data that is used to populate multiple areas throughout the site
    output: false
    icon: data_usage
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  default_content:
    path: content/default-content/
    icon: toolbar
  navigation_menus:
    path: data/menus
    description: Navigation menus you can use throughout the site.
    icon: menu
    output: false
    disable_add: false
    disable_add_folder: true
    disable_add_file_actions: false
    schemas:
      horizontal_subnav:
        path: .cloudcannon/schemas/horizontal-subnav.yml
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        create:
          path: data/menus
      primary_nav:
        path: .cloudcannon/schemas/primary-nav.yml
        reorder_inputs: true
        hide_extra_inputs: true
        remove_empty_inputs: false
        remove_extra_inputs: false
        create:
          path: data/menus
  pages:
    _enabled_editors:
      - visual
      - data
    path: content
    description: Pages description
    output: true
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      # page:
      #   path: .cloudcannon/schemas/page.md
      #   reorder_inputs: true
      #   hide_extra_inputs: false
      #   remove_empty_inputs: false
      #   remove_extra_inputs: false
      #   new_preview_url: /
      detail_page:
        path: .cloudcannon/schemas/detail-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: live-editor-previews/detail/
      detail_page_index:
        path: .cloudcannon/schemas/detail-page-index.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: live-editor-previews/detail/
        create:
          path: '[relative_base_path]/_index.md'
      guide_page:
        path: .cloudcannon/schemas/guide-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: live-editor-previews/guide/
      guide_page_index:
        path: .cloudcannon/schemas/guide-page-index.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: live-editor-previews/guide/
        create:
          path: '[relative_base_path]/_index.md'
  people:
    _enabled_editors:
      - data
      - visual
    path: content/people
    add_options:
      - name: Faculty Member
        schema: faculty
      - name: Speaker
        schema: speaker
      - name: Staff Member
        schema: staff
      - name: Student
        schema: student
    icon: group
    schemas:
      faculty:
        path: .cloudcannon/schemas/faculty-profile.md
        reorder_inputs: false
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /live-editor-previews/faculty-profile/
        create:
          path: '{last_name|slugify}-{first_name|slugify}.md'
      speaker:
        path: .cloudcannon/schemas/speaker.yml
      staff:
        path: .cloudcannon/schemas/staff.yml
      student:
        path: .cloudcannon/schemas/student-profile.md
        reorder_inputs: false
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /live-editor-previews/student-profile/
        create:
          path: '{last_name|slugify}-{first_name|slugify}.md'
  links:
    _enabled_editors:
      - data
    icon: link
    path: data/links.yml
    schemas:
      links:
        path: .cloudcannon/schemas/links.yml
  partners:
    _enabled_editors:
      - data
    path: data/partners.yml
    add_options:
      - name: Partner
        schema: partners
    icon: handshake
    schemas:
      partners:
        path: .cloudcannon/schemas/partners.yml
  places_and_spaces:
    _enabled_editors:
      - data
    path: content/places-and-spaces
    add_options:
      - name: Facility
        schema: facility
    icon: location_on
    schemas:
      facility:
        path: .cloudcannon/schemas/facilities.yml
        reorder_inputs: false
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        new_preview_url: /live-editor-previews/place/
  site_config:
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    icon: settings
    path: data/site_config
  sitewide_components:
    path: data/sitewide_components
    description: Sitewide components
    output: false
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    icon: variable_add
    schemas:
      sitewide_quicklinks:
        path: .cloudcannon/schemas/sitewide-quicklinks.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
collection_groups:
  - heading: Pages
    collections:
      - pages
      - articles
  - heading: Collections
    collections:
      - clubs_and_organizations
      - partners
      - people
      - places_and_spaces
  - heading: Site
    collections:
      - navigation_menus
      - site_config
      - default_content
      - sitewide_components
#   - heading: Site Config
#     collections:
#       - site_config
#   - heading: Data
#     collections:
#       - data
_enabled_editors:
  - visual
  - content
  - data
_select_data:
  alert_type:
    - name: Danger
      type: danger
    - name: Info
      type: info
    - name: Warning
      type: warning
  blend_modes:
    - name: Luminosity
      class: wvu-bg-blend-mode-luminosity
    - name: Lighten
      class: wvu-bg-blend-mode-lighten
  brand_colors:
    - name: WVU Gold
      background_classes: bg-wvu-gold text-wvu-blue
      class: wvu-gold
    - name: WVU Blue
      background_classes: bg-wvu-blue text-white
      class: wvu-blue
    - name: Accent - Blue
      background_classes: bg-wvu-accent--blue text-white
      class: wvu-accent--blue
    - name: Accent - Dark Blue
      background_classes: bg-wvu-accent--blue-dark text-white
      class: wvu-accent--blue-dark
    - name: Accent - Light Blue
      background_classes: bg-wvu-accent--blue-light text-wvu-blue
      class: wvu-accent--blue-light
    - name: Accent - Yellow
      background_classes: bg-wvu-accent--yellow text-dark
      class: wvu-accent--yellow
    - name: Accent - Old Gold
      background_classes: bg-wvu-accent--old-gold text-white
      class: wvu-accent--old-gold
    - name: Accent - Sunset
      background_classes: bg-wvu-accent--sunset text-dark
      class: wvu-accent--sunset
    - name: Neutral - Off-White
      background_classes: bg-wvu-neutral--off-white text-dark
      class: wvu-neutral--off-white
    - name: Neutral - Warm Gray Light
      background_classes: bg-wvu-neutral--warm-gray-light text-dark
      class: wvu-neutral--warm-gray-light
    - name: Neutral - Warm Gray Medium
      background_classes: bg-wvu-neutral--warm-gray-medium text-dark
      class: wvu-neutral--warm-gray-medium
    - name: Neutral - Warm Gray Dark
      background_classes: bg-wvu-neutral--warm-gray-dark text-white
      class: wvu-neutral--warm-gray-dark
    - name: Neutral - Cream
      background_classes: bg-wvu-neutral--cream text-dark
      class: wvu-neutral--cream
    - name: Neutral - Tan
      background_classes: bg-wvu-neutral--tan text-dark
      class: wvu-neutral--tan
  container_margins:
    - name: Default
      class: ""
    - name: Buffer Top
      class: mt-6
    - name: Buffer Bottom
      class: mb-6
    - name: Buffer Both
      class: my-6
    - name: Pull Up
      class: mt-n8
    - name: Pull Down
      class: mb-n8
    - name: Pull Both
      class: py-n8
  patterns:
    - name: Topo Map
      class: wvu-bg-topo-map
    - name: WV Pattern Grid
      class: wvu-bg-pattern-grid
    - name: WV Pattern Grid - Zoomed
      class: wvu-bg-pattern-grid-zoomed
  topper_margins:
    - name: Default
      class: ""
    - name: Buffer Bottom
      class: mb-6
    - name: Buffer Both
      class: my-6
  typography_palettes:
    - name: WVU Experience
      palette: wvu_experience
    - name: Down to Business
      palette: down_to_business
    - name: Discovery
      palette: discovery
    - name: Nostalgic
      palette: nostalgic
  vibes:
    - name: Down to Business
      value: down-to-business
    - name: Discovery
      value: discovery
    - name: WVU Experience
      value: wvu-experience
    - name: Nostalgic
      value: nostalgic
_inputs:
  alert_message:
    type: markdown
    cascade: true
  alert_status:
    type: switch
    cascade: true
  alert_type:
    type: select
    options:
      values:
        - _select_data.alert_type
      value_key: type
    cascade: true
  background_c:
    type: select
    label: Background Color
    options:
      values: _select_data.brand_colors
      value_key: background_classes
    cascade: true
  color:
    type: select
    options:
      allow_empty: true
      values:
        - _select_data.brand_colors
      value_key: class
    cascade: true
  column_a:
    type: object
    options:
      structures: _structures.column_blocks
    cascade: true
  column_b:
    type: object
    options:
      structures: _structures.column_blocks_sm
    cascade: true
  column_c:
    type: object
    options:
      structures: _structures.column_blocks_sm
    cascade: true
  copy:
    type: markdown
    options:
      show_count: true
  ctas:
    type: array
    options:
      structures: _structures.links
    cascade: true
  dir_include:
    hidden: true
  edit_mode_only:
    type: switch
    cascade: true
  excerpt:
    type: markdown
    cascade: true
  heading_c:
    type: select
    label: Heading Color
    options:
      values: _select_data.brand_colors
      value_key: class
    cascade: true
  hide:
    type: datetime
    cascade: true
  hide_collection_pages:
    type: switch
    cascade: true
  layout:
    hidden: true
    cascade: true
  limit:
    type: number
    cascade: true
  margin:
    type: select
    options:
      values: _select_data.container_margins
    cascade: true
  menu:
    type: select
    options:
      allow_empty: true
      structures: data.menus
    cascade: true
  message:
    type: markdown
    cascade: true
  person:
    type: select
    options:
      allow_empty: true
      values: data.people
    cascade: true
  postscript_links:
    type: array
    options:
      structures: _structures.links
    cascade: true
  publish_date:
    type: date
    instance_value: NOW
    cascade: true
  show:
    type: datetime
    cascade: true
  show_author_bios:
    type: switch
    cascade: true
  site_page:
    type: select
    options:
      allow_empty: true
      preview:
        text:
          - key: title
      values: data.site_pages
      value_key: id
    cascade: true
  sitewide_section:
    type: select
    options:
      allow_empty: true
      values: data.sitewide_components
    cascade: true
  src:
    type: image
    cascade: true
  student:
    type: select
    options:
      allow_empty: true
      values: data.people_data[?(@.schema == 'student')]
    cascade: true
  student_profile_topper:
    hidden: true
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      allow_empty: true
      values:
        - featured
    cascade: true
  text_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    cascade: true
  topper_type:
    hidden: true
  type:
    type: auto
    hidden: true
    cascade: true
  uuid:
    hidden: true
    instance_value: UUID
    cascade: true
  vibe:
    type: select
    options:
      values: _select_data.vibes
      value_key: value
    cascade: true
_structures:
  content_blocks:
    style: modal
  detail_blocks:
    style: modal
  links:
    values:
      - value:
          text:
          icon:
          url:
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    snippet: true
    strike: true
    styles: /assets/scss/custom/_content.scss
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
data_config: true
timezone: US/Eastern
_snippets:
_snippets_imports:
  hugo: false