spec:
  structures:
    - article_blocks
    - detail_blocks
    - place_blocks
  label: Rich Text Alt
  description:
  icon:
  tags: []
blueprint:
  textalt: My new Rich Text!
preview: This is a preview
_inputs:
  text:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      center: true
      code: true
      copyformatting: true
      embed: true
      expandable: true
      format:
      height:
      horizontalrule:
      image:
      image_size_attributes: true
      indent: true
      italic: true
      justify: true
      left: true
      link: true
      mime_type: true
      numberedlist: true
      outdent:
      paths:
      redo: true
      removeformat: true
      resize_style:
      right:
      snippet: 
      strike:
      styles: '/assets/css/editor.css'
      subscript:
      superscript:
      table:
      underline:
      undo:
      width:
